### ISSUE TITLE
Source name select is shown behind wizard buttons

### ISSUE THREAD

**Issue by jrusz** [osbuild/image-builder-frontend#1007]
I think this image says it all:

![image](https://user-images.githubusercontent.com/55534579/225271297-ca493951-e3e4-481f-8a7e-63af7298ec89.png)

I saw this in stage beta.

**Comment by jrusz** [comment]
I have found some more issues with this particular dropdown or maybe I should call it "select"

When I checked it out it seems it didn't return any items despite there were items to choose from. I compared it with the release select and that one worked as expected...

The release_select on the previous page:
```
(Pdb) self.release_dropdown
Select('.//*[@data-ouia-component-type="PF4/Select" and @data-ouia-component-id="release_select"]')
(Pdb) self.release_dropdown.items
['Red Hat Enterprise Linux (RHEL) 9', 'Red Hat Enterprise Linux (RHEL) 8', 'Show options for further development of RHEL']
```

The source_select:
```
(Pdb) self
Select('.//*[@data-ouia-component-type="PF4/Select" and @data-ouia-component-id="source_select"]')
(Pdb) self.items
[]
```

As you can see it returns an emtpy list. Is that related to this issue or it's something different?

**Comment by jrusz** [comment]
> I have found some more issues with this particular dropdown or maybe I should call it "select"
> 
> When I checked it out it seems it didn't return any items despite there were items to choose from. I compared it with the release select and that one worked as expected...
> 
> The release_select on the previous page:
> 
> ```
> (Pdb) self.release_dropdown
> Select('.//*[@data-ouia-component-type="PF4/Select" and @data-ouia-component-id="release_select"]')
> (Pdb) self.release_dropdown.items
> ['Red Hat Enterprise Linux (RHEL) 9', 'Red Hat Enterprise Linux (RHEL) 8', 'Show options for further development of RHEL']
> ```
> 
> The source_select:
> 
> ```
> (Pdb) self
> Select('.//*[@data-ouia-component-type="PF4/Select" and @data-ouia-component-id="source_select"]')
> (Pdb) self.items
> []
> ```
> 
> As you can see it returns an emtpy list. Is that related to this issue or it's something different?

This seems to be an issue with default locators in the widgetastic library. We can override those to fit this widget so it's probably fine :)

**Comment by lucasgarfield** [comment]
Resolved in both V1 and V2 wizards.
