### ISSUE TITLE
Review step: Incorrect count of the packages in Content expandable when recreating an image

### ISSUE THREAD

**Issue by regexowl** [osbuild/image-builder-frontend#1088]
When recreating an image the number of "Additional Red Hat and 3rd party packages" in the Review step's Content expandable is sometimes incorrect. Closing and re-opening the expandable seems to update the count to the correct one.

Same with the packages in the dual list selectors on "Additional Red Hat packages" step. Those can render as empty, but fill after interacting with another step.

![packages-issue](https://user-images.githubusercontent.com/49452678/233360602-fb17c8a5-1fee-4f4f-aac1-02c8adfe6f4a.gif)

**Comment by lucasgarfield** [comment]
This was an issue with the V1 wizard, I cannot reproduce with V2.
