### ISSUE TITLE
Image Builder | All: Pop out the Dropdowns!

### ISSUE THREAD

**Issue by regexowl** [osbuild/image-builder-frontend#1204]
PatternFly has a known bug that is blocking us from controlling the direction of the dropdown.

@lucasgarfield suggested we should revisit when we adopt PF5

**Comment by lucasgarfield** [comment]
We need to get the Wizard to have a fixed footer. The only scrollable area on the page will be inside the Wizard, and it will make sense for the dropdowns to open in that area. Closing this.
