### ISSUE TITLE
Question:  Why AWS target environment default region is eu-west-2

### ISSUE THREAD

**Issue by atodorov** [osbuild/image-builder-frontend#14]
Why is the default `eu-west-2` ? RHEL's default timezone is America/New York and IIRC AWS default region is `us-east-1`. 

Do you think we should change the defaults ?

We could also make this field into a select and just provide all of them but that's outside the scope of this question.

**Comment by dvdhrm** [comment]
Note that we use `us-east-2 (Ohio)` as default in most composer instances and a lot of data is already in S3 there.

**Comment by Gundersanne** [comment]
As the region is set by the image-builder service, this q is no longer relevant. We might allow the user to specific aws regions in future versions however.
