### ISSUE TITLE
Full screen Wizard needs a fixed footer

### ISSUE THREAD

**Issue by arburka** [osbuild/image-builder-frontend#1406]
The footer (and actions) require scrolling to see on certain common screen ratios.

A footer fixed to the screen would help the user understand the next steps

**Comment by lucasgarfield** [comment]
This problem will eventually be resolved (hopefully by Q1 2024) when we ditch our Data Driven Forms dependency... but I think I might be able to fix the problem now either with some hacky CSS or by submitting a patch to DDF... I'll look into it.

**Comment by arburka** [comment]
Sounds good @lucasgarfield!

**Comment by lucasgarfield** [comment]
Let's make sure the V2 wizard fixes this.

**Comment by regexowl** [comment]
Fixed by https://github.com/osbuild/image-builder-frontend/pull/2291
