### ISSUE TITLE
Disable navigation on the left

### ISSUE THREAD

**Issue by regexowl** [osbuild/image-builder-frontend#1616]
When user clicks to the Review step and then jumps back to another step the Wizard currently allows to change values and directly jump back to the Review step, evading possible disabled buttons. This can end up in this for example

![image](https://github.com/RedHatInsights/image-builder-frontend/assets/49452678/13d5a3c6-8177-4c63-953c-027486a8d0cf)

How to reproduce:
1. click through the Wizard to the Review step
2. click on "Amazon Web Services" in the navigation on the left
3. choose one of the radios, but don't fill in any values - the Next button should be disabled
4. click on the "Review" in the navigation on the left and jump to the Review step anyway

**Comment by ezr-ondrej** [comment]
IMO this would be fixed with using the new validation, we would highlight errors on the step and disable creating the image. User can freely jump around the wizard if they wish to, but will always know what's wrong.

**Comment by regexowl** [comment]
The validation via `useValidation` solves this problem.
