### ISSUE TITLE
Back button should be disable in Image Output step

### ISSUE THREAD

**Issue by mgold1234** [osbuild/image-builder-frontend#1629]
_description:_
1) open the new wizrd to create image
2) choose any target environemt
3) press on next button
4) press on back button
_actual:_
Back button is enable in Image Output step and when user press on it blank screen is open 
<img width="1090" alt="Screenshot 2024-02-05 at 12 17 47" src="https://github.com/RedHatInsights/image-builder-frontend/assets/73419853/3957003a-e9c9-4ed1-bdbd-bf9b077b307e">
<img width="1320" alt="Screenshot 2024-02-05 at 12 17 58" src="https://github.com/RedHatInsights/image-builder-frontend/assets/73419853/da709351-4d37-40bd-89b8-2cb3a6a89beb">

_expected:_ 
Back button should be disable in Image Output step

**Comment by regexowl** [comment]
Fixed by https://github.com/osbuild/image-builder-frontend/pull/1981
