### ISSUE TITLE
Chromium clickable cards bug

### ISSUE THREAD

**Issue by lucasgarfield** [osbuild/image-builder-frontend#1687]
We need to make sure https://github.com/patternfly/patternfly/issues/6352 is resolved before we ship the blueprints table.

**Comment by ezr-ondrej** [comment]
It's fixed! :tada:
https://github.com/patternfly/patternfly/pull/6364#issuecomment-1970040402

**Comment by lucasgarfield** [comment]
> It's fixed! 🎉 [patternfly/patternfly#6364 (comment)](https://github.com/patternfly/patternfly/pull/6364#issuecomment-1970040402)

Then I'm closing this!

**Comment by ezr-ondrej** [comment]
AAnd it didn't work :/
https://github.com/osbuild/image-builder-frontend/pull/1741

**Comment by avitova** [comment]
We fixed this by several iterations of redesigning blueprint cards. :)
[#1864
](https://github.com/osbuild/image-builder-frontend/pull/1864)
