### ISSUE TITLE
[RFE] "OAuth permissions" text shortening

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/image-builder-frontend#170]
https://bugzilla.redhat.com/show_bug.cgi?id=1954598

"""
Description of problem: On "Target Environment - Upload to Azure" window, the "OAuth permissions" text is a bit longer and I would like to suggest a short version:

"To authorize Image Builder to push images to Microsoft Azure, the account owner must configure Image Builder as an authorized application and give it the role of "Contributor" to at least one resource group. 
Learn more about OAuth 2.0"
"""

**Comment by Gundersanne** [comment]
@katierik thoughts? I'd be ok with changing the text.

**Comment by katierik** [comment]
LGTM
