### ISSUE TITLE
Create allow list

### ISSUE THREAD

**Issue by lucasgarfield** [osbuild/image-builder-frontend#1709]
Currently, some images that have an OpenSCAP profile fail to build. This is because osbuild-composer fails when it attempts to disable a service that does not exist. For now, as a workaround, we should implement a hard-coded deny list in the front end.

**Comment by regexowl** [comment]
Addressed in https://github.com/osbuild/image-builder-frontend/pull/1895 fr V1 and https://github.com/osbuild/image-builder-frontend/pull/2002 for V2.
