### ISSUE TITLE
Too many create buttons and missing colors

### ISSUE THREAD

**Issue by tichomir** [osbuild/image-builder-frontend#1749]
Once a use goes to Image Builder and has no images created, there perhaps too many "Create" buttons on the screen. currently there are 3. 

The one in the TOP Frame is not colored, while the other 2 are colored.

**Comment by regexowl** [comment]
Blueprints empty state was updated, currently having one primary "Create blueprint" button and a smaller "Add blueprint" link variant in the Blueprints sidebar.

![image](https://github.com/osbuild/image-builder-frontend/assets/49452678/50c3739b-f72b-4162-b0dc-243188a40b62)
