### ISSUE TITLE
Unselecting a blueprint card make the Version in the list view to disappear - changes to N/A

### ISSUE THREAD

**Issue by tichomir** [osbuild/image-builder-frontend#1753]
SSIA

![image](https://github.com/osbuild/image-builder-frontend/assets/6328657/33086601-21c6-4500-8fbf-efec3d44f66a)

**Comment by amirfefer** [comment]
This happens because these two different endpoints 
`/composes` doesn't return the corresponding blueprint version
`/blueprint/{id}/composes` does

https://github.com/osbuild/image-builder/pull/1046 should fix this issue

**Comment by regexowl** [comment]
Fixed in https://github.com/osbuild/image-builder/pull/1151
