### ISSUE TITLE
Chosing OpenSCAP Profile vs Chosing Compliance Policy?

### ISSUE THREAD

**Issue by tichomir** [osbuild/image-builder-frontend#1755]
I am not sure what is the agreement here, however the general thinking was that: 

1. Customers will be able to select Compliance Policies rather the OpenSCAP profiles? 

There is almost no customer that will just apply a compliance SCAP profile as is, all of them will be looking into modifying them as Compliance Service part of Insights offers today. 

2. We shouldn't be really calling out OpenSCAP, rather Compliance?

**Comment by regexowl** [comment]
Compliance is being introduced by https://github.com/osbuild/image-builder-frontend/pull/2440
