### ISSUE TITLE
When a chosen blueprint is cleared, it's still marked as selected

### ISSUE THREAD

**Issue by amirfefer** [osbuild/image-builder-frontend#1766]
https://github.com/osbuild/image-builder-frontend/assets/11807069/e42da53e-89a8-49ad-9f7f-2e787fa7c99b

**Comment by amirfefer** [comment]
This seems to be a patternfly bug, I've tried to add a control `isSelected` prop, but it doesn't fix the issue

**Comment by ezr-ondrej** [comment]
Another PF bug? :(

**Comment by amirfefer** [comment]
https://github.com/patternfly/patternfly-react/issues/10136

**Comment by amirfefer** [comment]
a suggestion from PatternFly is to use the deprecated `isSelectableRaised` and `hasSelectableInput` props
looks like it works!

https://github.com/osbuild/image-builder-frontend/assets/11807069/15d75770-b18a-49e4-9217-db7beaa5f91e

**Comment by jrusz** [comment]
So that patternfly bug is also the reason I can't deselect the blueprint by clicking it again?
