### ISSUE TITLE
Bug- recreate image

### ISSUE THREAD

**Issue by kelseamann** [osbuild/image-builder-frontend#1824]
Was giving a demo of this yesterday, noticed that when I select "Recreate image" from the kebab in the images menu, the Review step in the wizard flashes for a second before the image is recreated. confusing for the user- take this out so they know there is only one way to access the review screen, which is through "Edit blueprint".

**Comment by lucasgarfield** [comment]
We've removed "Recreate image" functionality, even for blueprint-less images (users should migrate to using blueprints and the 'build images' function).
