### ISSUE TITLE
UI mistake- use "Menu toggle" not "split button"

### ISSUE THREAD

**Issue by kelseamann** [osbuild/image-builder-frontend#1826]
![Screenshot 2024-03-20 at 11 56 02 AM](https://github.com/osbuild/image-builder-frontend/assets/91503095/d9b30047-9ba3-4933-b4cd-13d04db00359)
In the review screen where the user an choose to "save" or "save and build" I meant to use a menu toggle WITH AN ACTION, so user can just press "save". Instead in the mocks I used a split action button, where the user is forced to enter the dropdown. Correct version look like the screenshot- https://www.patternfly.org/components/menus/menu-toggle#split-button-toggle-with-action

**Comment by jrusz** [comment]
Agreed, the first time I interacted with it I expected the save to just save it and only the dropdown part to show the dropdown, it's annoying right now when you have to basically click it twice to do what you'd expect to be done with single click.
