### ISSUE TITLE
V2: building an image shows "Blueprint is being built" popup which doesn't make sense IMO

### ISSUE THREAD

**Issue by jrusz** [osbuild/image-builder-frontend#1854]
![image](https://github.com/osbuild/image-builder-frontend/assets/55534579/27f48478-37d4-4538-b035-ec4b57ca8eb0)

**Comment by amirfefer** [comment]
I agree, should be `image`
 duplicate of https://github.com/osbuild/image-builder-frontend/issues/1823

**Comment by jrusz** [comment]
Ah ok didn't notice that one, thanks!
