### ISSUE TITLE
 configuration type alwyas 'automatic' when user edit blueprint 

### ISSUE THREAD

**Issue by mgold1234** [osbuild/image-builder-frontend#2017]
1) user press on Edit blueprint - blueprint with file system configuration
2) open  'file system configuration'
actual:
 configuration type alwyas 'automatic' when user edit blueprint 
<img width="426" alt="Screenshot 2024-04-26 at 19 19 18" src="https://github.com/osbuild/image-builder-frontend/assets/73419853/0eacb07f-870f-4ede-ac05-1e41ebbffbe5">

**Comment by regexowl** [comment]
Fixed in https://github.com/osbuild/image-builder-frontend/pull/2014/commits/02055746dacc6064e23dc85614f3387bd76ece0e
