### ISSUE TITLE
Pagination on packages step is broken

### ISSUE THREAD

**Issue by ezr-ondrej** [osbuild/image-builder-frontend#2084]
[Screencast from 2024-05-17 10-42-17.webm](https://github.com/osbuild/image-builder-frontend/assets/2884324/d04fbc32-87a0-4855-b3e9-73df9bc69f6d)

**Comment by ezr-ondrej** [comment]
Also noticed in https://github.com/osbuild/image-builder-frontend/pull/2050#discussion_r1609627243

**Comment by Andrewgdewar** [comment]
hmmm, I wonder if I forget to do the same thing here. 
Will look.

**Comment by Andrewgdewar** [comment]
Yeah I forgot to add both perPage/page values to the useMemo there. As the data is cached, those are needed.
