### ISSUE TITLE
Details step is disabled on blueprint edit

### ISSUE THREAD

**Issue by jrusz** [osbuild/image-builder-frontend#2220]
When editing a blueprint I can't go to the Details step, I have to walk through the wizard to get there which I believe was not the case before. Also the tests are failing on this as when they get to this step the Next button is disabled.

![disabled-step](https://github.com/osbuild/image-builder-frontend/assets/55534579/3a36eb37-28f9-4dba-b160-6e5d6935dfb8)

**Comment by ezr-ondrej** [comment]
That will be my fault :(

**Comment by jrusz** [comment]
Sounds like something that should have been caught by unit tests...

**Comment by ezr-ondrej** [comment]
> Sounds like something that should have been caught by unit tests...

Yes, I'll try to figure out where we have a gap while fixing it and add the proper unit test coverage.

**Comment by ezr-ondrej** [comment]
I've opened a PR with a unit test :)

**Comment by jrusz** [comment]
The Next button is still disabled on the step 
![image](https://github.com/osbuild/image-builder-frontend/assets/55534579/2fb17faa-6b36-4d46-af21-87d0b0907c03)

**Comment by ezr-ondrej** [comment]
I can't really reproduce this :(
@jrusz what exactly the test does? :thinking:

**Comment by jrusz** [comment]
> I can't really reproduce this :( @jrusz what exactly the test does? 🤔

Steps to reproduce on stage:

1. Create new blueprint
2. Select just guest image
3. Register later
4. Keep clicking next until Details step where you fill name
5. Create blueprint
6. Edit the blueprint
7. Change to RHEL-8 and select guest image again
8. Click next until Details step
9. Next button is disabled even if you change name
