### ISSUE TITLE
ova and vmdk radios are not aligned properly

### ISSUE THREAD

**Issue by lucasgarfield** [osbuild/image-builder-frontend#2549]
![image](https://github.com/user-attachments/assets/b7c08282-a4d6-445c-a85b-5fba6f28ca14)

**Comment by regexowl** [comment]
Fixed by https://github.com/osbuild/image-builder-frontend/pull/2619

![image](https://github.com/user-attachments/assets/0e8ac2b4-0d64-4df4-ac45-eb5e8d7004e7)
