### ISSUE TITLE
Re-enable colorful icons in the images list

### ISSUE THREAD

**Issue by ochosi** [osbuild/image-builder-frontend#2611]
For some reason our icons in the images table have turned symbolic aka monochrome. I wonder why and it doesn't help with readability (from my pov), i.e. the yellow triangle really draws attention.

**Comment by ezr-ondrej** [comment]
Would you have a screenshot? :)

**Comment by ochosi** [comment]
Now:
![image](https://github.com/user-attachments/assets/ad1cbd49-0fdb-4250-b1dd-a054b398030f)

What it should look like:
![image](https://github.com/user-attachments/assets/20685245-e223-4564-8ef5-c55e83f46833)
