### ISSUE TITLE
Add jest snapshot testing

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/image-builder-frontend#7]
Running snapshot tests with jest is common with clouddot ui projects. Let's start with a very basic test to get the ball rolling.

Examples: https://github.com/RedHatInsights/insights-rbac-ui/tree/master/src/test

**Comment by atodorov** [comment]
FTR / QE notes from @Gundersanne :

> this is just to establish a way of testing. Like the first test could just load the page and make sure that the button sends you to the wizard. But the next additions to the FE would be to add that dynamic content for arches/images/distributions etc...

**Comment by jkozol** [comment]
Closed by #16
