### ISSUE TITLE
CreateImageWizard: just clicking `Next` shouldn't lead to error

### ISSUE THREAD

**Issue by teg** [osbuild/image-builder-frontend#93]
It would be great if clicking `Next` without changing anything either gave correct defaults (that would not error out in review) or wouldn't work at all (greyed out `Next` button?).

- We should require at least one cloud provider to be selected, if none is, disable the `Next` button.
- If AWS is selected, don't allow going past the `Upload to AWS` screen unless a 12-digit account number has been entered.
- Default to not register, and if registering is enabled, require an activation key (do we have a way to verify at least the format?)
- If the Review screen has errors, disable the `Create` button, now we can go ahead and create an image that we know will fail.

**Comment by jkozol** [comment]
Closing this and splitting into #110 #111 #112 #113
