### ISSUE TITLE
CreateImageWizard: don't allow creating more than one compose at once

### ISSUE THREAD

**Issue by teg** [osbuild/image-builder-frontend#94]
There is a significant delay between clicking the `Create` button and the landing page appearing. That's ok (intended), but we should make sure the `Create` button can only be clicked once (greyed out once it has been?). Possibly also show a pending graphic while we wait.

**Comment by Gundersanne** [comment]
I agree with this, but we might need some input here from @katierik here.

**Comment by katierik** [comment]
WIP design on this -- https://marvelapp.com/prototype/6g7dja9/screen/76873728

Will be updating but we want a combo of Option 1 (optimistic) and Option 3 (wait until we can go optimistic)

**Comment by Gundersanne** [comment]
With the optimistic UI pattern, should we immediately return to the landing page when sending the request? (that is before we get the response back) And then show the notification when we receive the response?

**Comment by Gundersanne** [comment]
This has been fixed for a while now, more specifically in #101 , I really should get better about adding `Fix #issue` :)
